# Generated by Django 3.1.3 on 2020-12-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['-add_datetime'], 'verbose_name': 'Набор товаров', 'verbose_name_plural': 'Наборы товаров'},
        ),
    ]
